CREATE TABLE `batch_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`jobType` enum('catalog_update','catalog_delete','report_generation') NOT NULL,
	`config` json NOT NULL,
	`status` enum('queued','running','completed','failed','cancelled') NOT NULL DEFAULT 'queued',
	`progress` int DEFAULT 0,
	`currentBatch` int DEFAULT 0,
	`totalBatches` int DEFAULT 0,
	`processedItems` int DEFAULT 0,
	`totalItems` int DEFAULT 0,
	`successCount` int DEFAULT 0,
	`errorCount` int DEFAULT 0,
	`warningCount` int DEFAULT 0,
	`handles` json,
	`errors` json,
	`statusMessage` text,
	`queuedAt` timestamp NOT NULL DEFAULT (now()),
	`startedAt` timestamp,
	`completedAt` timestamp,
	`historyId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `batch_jobs_id` PRIMARY KEY(`id`)
);
