CREATE TABLE `schedule_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scheduleId` int NOT NULL,
	`userId` int NOT NULL,
	`triggerType` enum('auto','manual') NOT NULL DEFAULT 'auto',
	`totalJobs` int DEFAULT 0,
	`completedJobs` int DEFAULT 0,
	`failedJobs` int DEFAULT 0,
	`totalItems` int DEFAULT 0,
	`totalSpend` bigint,
	`totalImpressions` bigint,
	`catalogItemsUpdated` int DEFAULT 0,
	`catalogErrors` int DEFAULT 0,
	`status` enum('running','completed','partial','failed') NOT NULL DEFAULT 'running',
	`errorMessage` text,
	`jobIds` json,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`durationMs` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `schedule_runs_id` PRIMARY KEY(`id`)
);
